### ISSUE TITLE
怀着一丝丝希望来开个issue，导入zrm2000配置后无法正常使用

### ISSUE THREAD

**Issue by HoldOnBro** [henices/rime#1]
问题是，使用zrm2000输入只输出英文字母，不会出现文字。。。是我配置导入的问题还是需要更改特定设置？网上到处找rime的带辅码的自然码方案，独此一家QAQ
@henices

**Comment by henices** [comment]
这是配置问题  回头我写个文档 可以使用的

**Comment by HoldOnBro** [comment]
感激不尽！！！

**Comment by HoldOnBro** [comment]
网上又看了看,发现这篇文章
[Rime输入法](http://einverne.github.io/post/2014/11/Rime.html)
其中提到：

> 关于词库，Rime输入法的词库有两部分组成。以下摘自贴吧：
> 
> 一部分是由系统文本词库（一般以xxx.dict.yaml结尾）通过「重新部署/deploy」生成的固态词典（一般以xxx.table.bin结尾），这部份词库因为在输入过程是固定不変的，所以存在用大量的词彚，也不允许用戸来直接删除。

然后让我回想起了之前看用户文件夹的时候找到的一个文件夹内的确有专门存这些东西

path:
`C:\Users\MyName\AppData\Roaming\Rime\build`
然后把这份词库内的两个文件:
`zrm2000.dict.yaml`
和
`zrm2000.schema.yaml`
放进去后,再重新部署
锵锵! done!~

P.S
当然,
`zrm2000.dict.yaml`
 `zrm2000.schema.yaml`
这两个文件首先还得先放到
`C:\Users\MyName\AppData\Roaming\Rime`
这个根目录下
否则输入法设定里面就找不到自然码2000啦
