### ISSUE TITLE
请问zrm2000这个RIME配置还有其他码表/词库吗？

### ISSUE THREAD

**Issue by lippmann** [henices/rime#2]
貌似zrm2000.schema.yaml是没办法和luna_pinyin共用其他词库的，除了本身的码表外，请问还有其他词库或码表吗？

感谢这个zrm2000的方案，非常好用！

**Comment by henices** [comment]
没有了，词库问题我没研究，我都是用自己的词库。

**Comment by lippmann** [comment]
感谢回复，但是 zrm2000.dict.yaml 加入自定义码表似乎没有用？请问需要特别设置吗？

**Comment by henices** [comment]
https://github.com/henices/rime/issues/1

**Comment by lippmann** [comment]
噗，我的意思是，zrm2000.dict.yaml 本身是可以使用的，但是这个文件里面我自己添加的自定义码表不行。比如原码表里面是没有卤肉饭这个词，我在「#用户自定义码表」下添加编码「卤肉饭 lurbfj 」后重新部署，依然无法打出。也曾经试图批量导入过自制的码表，但也不行。

是因为格式不对吗？我看原码表中文和编码之间的空格非常小，只有正常空格的一半。

PS，我是学文科的，不太懂代码，请见谅。
